planner:
  expand: true

stages:
  - name: buildTTGateway
    transformations:
      - checkout
      - compile

transformations:
  - name: checkout
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://gitlab.bitsolve.de/doering-thesis/ttgateway2.git
      branch: pipeline
      credentials:
        type: plain
        username: ma_pipeline
        password: test2345

  - name: compile
    service: maven-service
    command: compile
