planner:
  expand: true
  hints:
    - type: schedule
      target: deployToArtifactory
      after: jmeter

stages:
  - name: buildTTGateway
    transformations:
      - checkout
      - compile
      - assemble
#  - name: bakeTTGateway
#    transformations:
#      - buildContainer
#  - name: deployTTGateway
#    transformations:
#      - deployToArtifactory

transformations:
  - name: checkout
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://gitlab.bitsolve.de/doering-thesis/ttgateway2.git
      branch: pipeline
      credentials:
        type: plain
        username: ma_pipeline
        password: test2345

  - name: compile
    service: maven-service
    command: compile

  - name: assemble
    service: maven-service
    command: assemble

#  - name: buildContainer
#    service: docker-service
#    command: buildTTGateway

#  - name: deployToArtifactory
#    service: maven-service
#    command: deploy

assessments:
  - name: cobertura
    service: maven-service
    command: cobertura

#  - name: jmeter
#    service: docker-service
#    command: jmeterTTGateway

qualityGates:
  - strategy: auto
    policies:
      - name: PassedTestRate
        interpretation: threshold
        actualValue: passedRate
        setPoint: 1
      - name: LineCoverage
        interpretation: threshold
        actualValue: lineCoverage
        setPoint: 0
#      - name: AvgResponseTime
#        interpretation: threshold
#        actualValue: avgResponseTimeMs
#        setPoint: 400
#      - name: ResponseSuccessRate
#        interpretation: threshold
#        actualValue: successRate
#        setPoint: 0.85
